### ISSUE TITLE
HazardTracker doesn't synchronize correctly?

### ISSUE THREAD

**Issue by tomtomjhj** [roghnin/Interval-Based-Reclamation#2]
Hi. I found out that your implementation of HP doesn't seem to synchronize properly.
Up to my knowledge, a read-write fence should be inserted
* after writing to the hazard pointer list (to protect a pointer), and
* before reading from hazard pointer list.

So there should be a fence at
https://github.com/roghnin/Interval-Based-Reclamation/blob/fdd6f6559d2d8e98e70dcb3c4d3d457f456302ed/src/trackers/HazardTracker.hpp#L108-L109
and
https://github.com/roghnin/Interval-Based-Reclamation/blob/fdd6f6559d2d8e98e70dcb3c4d3d457f456302ed/src/trackers/HazardTracker.hpp#L52-L53

Here are the examples from folly:

https://github.com/facebook/folly/blob/11003288fe0a3489fe968c4a4c5d9806945f404c/folly/synchronization/HazptrHolder.h#L124-L136

https://github.com/facebook/folly/blob/11003288fe0a3489fe968c4a4c5d9806945f404c/folly/synchronization/HazptrDomain.h#L490-L507

**Comment by roghnin** [comment]
Hi,

Thanks for the question.

First of all, could you clarify what do you mean by "read-write fence" in this situation? Do you mean a "full fence" where any read/write operation before the fence cannot be reordered after the fence, and vice versa?

If that's the case, I believe memory ordering provided by the code in the repo is enough. slots[] is (effectively) an array of std::atomic values (pointers), where operator '=' is equivalent to std::atomic::store():
https://en.cppreference.com/w/cpp/atomic/atomic/operator%3D
and in turn provides sequential consistency semantics:
https://en.cppreference.com/w/cpp/atomic/atomic/store

The store itself acts as a memory fence here, and I failed to argue that it might cause any synchronization issue. The example in folly provides a rather comprehensive implementation of memory fence, while we opted for C++11 standard library.

Please let me know if I'm wrong.

**Comment by tomtomjhj** [comment]
Hi.
By "fence" I meant exactly what you described. I knew that `=` is basically `atomic::store` but I thought it uses `memory_order::release` by default instead of `seq_cst`, which made me think that your implementation is probably incorrect. Now I'm convinced that your implementation is correct. I should've check the documentation.
But I'm still confused about the precise semantics of SC accesses in C/C++ standard. Maybe I should take time to read thoroughly about it.

Thanks!
