### ISSUE TITLE
Potential off-by-one error in RangeTrackerNew

### ISSUE THREAD

**Issue by elfprince13** [roghnin/Interval-Based-Reclamation#3]
I believe this sequence of code:
https://github.com/roghnin/Interval-Based-Reclamation/blob/281d38799574f422bc694a187195ceaf03f120c7/src/trackers/RangeTrackerNew.hpp#L155-L158

Should be changed to:
```c++
		retire_counters[tid]=retire_counters[tid]+1;
		if(collect && retire_counters[tid]%freq==0){
			empty(tid);
		}
```

I believe this for several reasons:
- If the goal is intermittent `empty`ing, it doesn't make sense to collect after your first `retire`.
- The modified logic parallels the order of operations in `alloc`: https://github.com/roghnin/Interval-Based-Reclamation/blob/281d38799574f422bc694a187195ceaf03f120c7/src/trackers/RangeTrackerNew.hpp#L85-L88
- Averts an underflow when `empty` calls `dec_retired` before `retire_counters` has been increments.

**Comment by elfprince13** [comment]
If this change is correct, the error may be present in other files as well, but I didn't check the other.

**Comment by roghnin** [comment]
Sorry for the late response.
I believe you're correct. Thanks for bringing this up.
I'll double check it and push the patch shortly.
